import { NextRequest, NextResponse } from "next/server";
import Stripe from "stripe";
import { createAdminClient } from "@/lib/supabase/admin";
import { getStripeClient } from "@/lib/stripe/client";
import { PLAN_CONFIG, planForPriceId } from "@/lib/stripe/plans";

// Stripe needs Node's crypto to verify signatures — pin off the edge runtime.
export const runtime = "nodejs";

// Stripe moved billing-period fields off Subscription onto each
// SubscriptionItem (a subscription can now mix items with different
// cycles) — we only ever create single-item subscriptions, so item 0 is
// always the one that matters here.
function periodEndIso(subscription: Stripe.Subscription): string | null {
  const end = subscription.items.data[0]?.current_period_end;
  return end ? new Date(end * 1000).toISOString() : null;
}

// Stripe also replaced Invoice.subscription with a `parent.subscription_details`
// object (invoices can now be generated by things other than subscriptions).
function invoiceSubscriptionId(invoice: Stripe.Invoice): string | null {
  const sub = invoice.parent?.subscription_details?.subscription;
  if (!sub) return null;
  return typeof sub === "string" ? sub : sub.id;
}

async function userIdForCustomer(customerId: string): Promise<string | null> {
  const admin = createAdminClient();
  const { data } = await admin
    .from("profiles")
    .select("id")
    .eq("stripe_customer_id", customerId)
    .maybeSingle();
  return data?.id ?? null;
}

// POST /api/webhooks/stripe — exempted from session auth in middleware.ts
// (Stripe calls this with no cookies at all). Signature verification below
// is what actually authenticates the caller.
export async function POST(req: NextRequest) {
  const sig = req.headers.get("stripe-signature");
  const rawBody = await req.text();

  if (!sig) {
    return NextResponse.json({ error: "missing signature" }, { status: 400 });
  }

  const stripe = getStripeClient();
  let event: Stripe.Event;
  try {
    event = stripe.webhooks.constructEvent(rawBody, sig, process.env.STRIPE_WEBHOOK_SECRET!);
  } catch (err) {
    console.warn("[stripe webhook] signature verification failed:", err);
    return NextResponse.json({ error: "invalid signature" }, { status: 400 });
  }

  const admin = createAdminClient();

  switch (event.type) {
    case "checkout.session.completed": {
      const session = event.data.object as Stripe.Checkout.Session;
      if (session.mode !== "subscription" || !session.subscription) break;

      const userId = session.client_reference_id;
      if (!userId) break;

      const subscription = await stripe.subscriptions.retrieve(session.subscription as string);
      const priceId = subscription.items.data[0]?.price.id;
      const plan = priceId ? planForPriceId(priceId) : null;
      if (!plan) break;

      await admin
        .from("profiles")
        .update({
          plan,
          stripe_subscription_id: subscription.id,
          subscription_status: subscription.status,
          current_period_end: periodEndIso(subscription),
        })
        .eq("id", userId);

      await admin.rpc("grant_credits", {
        p_user_id: userId,
        p_amount: PLAN_CONFIG[plan].credits,
        p_type: "subscription_grant",
        p_reference_id: null,
        p_idempotency_key: `stripe_checkout:${session.id}`,
      });
      break;
    }

    case "customer.subscription.updated": {
      const subscription = event.data.object as Stripe.Subscription;
      const userId =
        subscription.metadata?.user_id || (await userIdForCustomer(subscription.customer as string));
      if (!userId) break;

      const priceId = subscription.items.data[0]?.price.id;
      const plan = priceId ? planForPriceId(priceId) : null;

      await admin
        .from("profiles")
        .update({
          ...(plan ? { plan } : {}),
          subscription_status: subscription.status,
          current_period_end: periodEndIso(subscription),
        })
        .eq("id", userId);
      break;
    }

    case "customer.subscription.deleted": {
      const subscription = event.data.object as Stripe.Subscription;
      const userId =
        subscription.metadata?.user_id || (await userIdForCustomer(subscription.customer as string));
      if (!userId) break;

      await admin
        .from("profiles")
        .update({ plan: "free", subscription_status: "canceled" })
        .eq("id", userId);
      break;
    }

    case "invoice.payment_succeeded": {
      const invoice = event.data.object as Stripe.Invoice;
      // First invoice of a subscription is already handled by
      // checkout.session.completed — only renewals grant credits here.
      if (invoice.billing_reason !== "subscription_cycle") break;

      const subscriptionId = invoiceSubscriptionId(invoice);
      if (!subscriptionId) break;

      const userId = await userIdForCustomer(invoice.customer as string);
      if (!userId) break;

      const subscription = await stripe.subscriptions.retrieve(subscriptionId);
      const priceId = subscription.items.data[0]?.price.id;
      const plan = priceId ? planForPriceId(priceId) : null;
      if (!plan) break;

      await admin.rpc("grant_credits", {
        p_user_id: userId,
        p_amount: PLAN_CONFIG[plan].credits,
        p_type: "subscription_grant",
        p_reference_id: null,
        p_idempotency_key: `stripe_invoice:${invoice.id}`,
      });

      await admin
        .from("profiles")
        .update({ current_period_end: periodEndIso(subscription) })
        .eq("id", userId);
      break;
    }

    case "invoice.payment_failed": {
      const invoice = event.data.object as Stripe.Invoice;
      const userId = await userIdForCustomer(invoice.customer as string);
      if (!userId) break;

      await admin.from("profiles").update({ subscription_status: "past_due" }).eq("id", userId);
      break;
    }

    default:
      break;
  }

  return NextResponse.json({ received: true });
}
