import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — AI Scope by Marcstrat",
  description: "Read the Terms of Service for AI Scope by Marcstrat.",
};

export default function TermsPage() {
  const updated = "May 23, 2026";

  return (
    <div style={{ minHeight: "100vh", background: "var(--c-bg)", color: "var(--c-text)" }}>
      <Navbar />

      <main className="max-w-3xl mx-auto px-6 py-16">
        <div className="mb-10">
          <span
            className="inline-block text-[10px] font-mono font-bold px-3 py-1 rounded-full mb-4"
            style={{ color: "var(--c-accent2)", background: "rgba(124,111,255,0.08)", border: "1px solid rgba(124,111,255,0.2)", letterSpacing: 2 }}
          >
            LEGAL
          </span>
          <h1 className="text-3xl font-extrabold mb-2" style={{ color: "var(--c-text)" }}>
            Terms of Service
          </h1>
          <p className="text-sm" style={{ color: "var(--c-muted)" }}>
            Last updated: {updated}
          </p>
        </div>

        <div className="flex flex-col gap-8 text-sm leading-relaxed" style={{ color: "var(--c-text-sub)" }}>
          <section>
            <h2 className="text-base font-bold mb-2" style={{ color: "var(--c-text)" }}>1. Acceptance of Terms</h2>
            <p>
              By accessing or using AI Scope (&quot;the Service&quot;), operated by Marcstrat, you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold mb-2" style={{ color: "var(--c-text)" }}>2. Description of Service</h2>
            <p>
              AI Scope is an AI visibility and brand monitoring platform that queries multiple AI providers (including OpenAI, Google Gemini, and Perplexity) to measure and improve your brand&apos;s presence in AI-generated responses.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold mb-2" style={{ color: "var(--c-text)" }}>3. Eligibility</h2>
            <p>
              You must be at least 18 years old and capable of forming a binding contract to use the Service. By using AI Scope, you represent that you meet these requirements.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold mb-2" style={{ color: "var(--c-text)" }}>4. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="mt-2 flex flex-col gap-1 pl-4 list-disc">
              <li>Use the Service for any unlawful purpose.</li>
              <li>Attempt to reverse-engineer, scrape, or abuse the platform infrastructure.</li>
              <li>Submit prompts containing harmful, deceptive, or illegal content.</li>
              <li>Resell or sublicense access to the Service without written permission.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-bold mb-2" style={{ color: "var(--c-text)" }}>5. Intellectual Property</h2>
            <p>
              All content, design, and code within AI Scope is the property of Marcstrat unless otherwise noted. You retain ownership of any data you submit. By submitting content, you grant Marcstrat a limited license to process it solely for providing the Service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold mb-2" style={{ color: "var(--c-text)" }}>6. Third-Party AI Providers</h2>
            <p>
              AI Scope relies on third-party AI APIs. We are not responsible for the accuracy, availability, or content of responses generated by those providers. Their respective terms of service also apply to your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold mb-2" style={{ color: "var(--c-text)" }}>7. Disclaimer of Warranties</h2>
            <p>
              The Service is provided &quot;as is&quot; without warranties of any kind, express or implied. Marcstrat does not guarantee that the Service will be uninterrupted, error-free, or that results will be accurate.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold mb-2" style={{ color: "var(--c-text)" }}>8. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Marcstrat shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold mb-2" style={{ color: "var(--c-text)" }}>9. Modifications</h2>
            <p>
              We reserve the right to update these Terms at any time. The &quot;Last updated&quot; date will reflect the most recent change. Continued use of the Service after changes constitutes acceptance of the new Terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold mb-2" style={{ color: "var(--c-text)" }}>10. Contact</h2>
            <p>
              Questions about these Terms? Contact us at{" "}
              <a href="mailto:legal@marcstrat.com" style={{ color: "var(--c-accent)" }} className="underline">
                legal@marcstrat.com
              </a>.
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
