import LegalPage from "@/components/LegalPage";

function H2({ children }: { children: React.ReactNode }) {
  return (
    <h2 className="text-xl font-semibold mb-3" style={{ color: "var(--text)" }}>
      {children}
    </h2>
  );
}

export default function TermsOfServicePage() {
  return (
    <LegalPage title="Terms of Service" updated="July 21, 2026">
      <p>
        These terms govern your use of AiScope, an AI-visibility auditing tool operated by Marcstrat, currently
        available as a public beta. By creating an account, you agree to these terms.
      </p>

      <section>
        <H2>Beta service: no uptime or accuracy guarantee</H2>
        <p>
          AiScope is in active beta. Features, pricing, and scoring methodology may change without notice, and we
          don't guarantee uninterrupted availability. Scores and recommendations are generated by third-party AI
          models (Gemini, ChatGPT, Perplexity) and are provided as guidance, not a warranty of how any given AI
          system will treat your site.
        </p>
      </section>

      <section>
        <H2>Accounts</H2>
        <p>
          Anyone can create an account with Google or an email and password. We reserve the right to suspend
          accounts or limit access at our discretion during the beta period, including to manage capacity or
          address abuse.
        </p>
      </section>

      <section>
        <H2>Acceptable use</H2>
        <p>
          You agree not to use AiScope to scan websites you don't have the right to audit for malicious purposes, to
          circumvent rate limits or credit systems, to resell or redistribute scan results as your own product
          without a paid plan that permits it (see Pricing), or to attempt to disrupt or reverse-engineer the
          service.
        </p>
      </section>

      <section>
        <H2>Plans and credits</H2>
        <p>
          Free accounts include a limited number of scans per day. Paid plans (Pro, Agency, and any limited-time
          Lifetime offer) unlock additional scan volume, models, bulk scanning, and history as described on the
          Pricing page at time of purchase. Credit balances and plan terms may be adjusted with notice as the
          product matures out of beta.
        </p>
      </section>

      <section>
        <H2>Limitation of liability</H2>
        <p>
          AiScope is provided "as is" during the beta period. To the fullest extent permitted by law, Marcstrat is
          not liable for indirect, incidental, or consequential damages arising from your use of the service,
          including decisions made based on scan results or AI-visibility scores.
        </p>
      </section>

      <section>
        <H2>Changes to these terms</H2>
        <p>
          We may update these terms as the product evolves, particularly as it exits beta. Continued use of AiScope
          after an update constitutes acceptance of the revised terms.
        </p>
      </section>
    </LegalPage>
  );
}
