"use client";

import { useState, useRef, useCallback } from "react";

// ── Types ──────────────────────────────────────────────────────────────────
interface ProviderResponse {
  provider: string;
  response: string;
  durationMs?: number;
  error?: string;
}

interface PromptResult {
  url: string;
  status: "pending" | "running" | "done" | "failed";
  // backwards-compatible primary fields
  response: string;
  provider?: string;
  durationMs?: number;
  error?: string;
  // new: multiple provider responses and which one is selected
  responses?: ProviderResponse[];
  selectedResponseIndex?: number;
}

// ── Default prompt template ────────────────────────────────────────────────
const DEFAULT_PROMPT = `You are an AI Visibility Auditor. Analyse the website at {url} and answer the following:

1. Is this website likely to be cited or referenced by AI assistants (ChatGPT, Gemini, Perplexity)?
2. What is the primary topic or industry of this site?
3. List 3 specific improvements that would increase its AI discoverability.
4. Rate its current AI visibility: Poor / Fair / Good / Excellent — and explain why.

Be concise but specific. Format your response clearly with numbered sections.`;

// ── Helpers ────────────────────────────────────────────────────────────────
function parseUrls(raw: string): string[] {
  return raw
    .split(/[\n,]+/)
    .map((u) => u.trim())
    .filter(Boolean)
    .map((u) => (u.startsWith("http") ? u : "https://" + u));
}

function msToSec(ms?: number) {
  return ms ? `${(ms / 1000).toFixed(1)}s` : "";
}

// ── PDF Export — plain text written with jsPDF, no HTML rendering ────────────
async function exportToPdf(results: PromptResult[], prompt: string) {
  // Load jsPDF from CDN once
  if (!(window as { jspdf?: unknown }).jspdf) {
    await new Promise<void>((resolve, reject) => {
      const script = document.createElement("script");
      script.src = "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js";
      script.onload = () => resolve();
      script.onerror = () => reject(new Error("Failed to load jsPDF"));
      document.head.appendChild(script);
    });
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { jsPDF } = (window as any).jspdf;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const doc: any = new jsPDF({ unit: "mm", format: "a4", orientation: "portrait" });

  const PW = 210;
  const PH = 297;
  const ML = 15;
  const MR = 15;
  const TW = PW - ML - MR;
  const LH = 5;   // line height mm
  let y = 15;

  const doneCnt = results.filter((r) => r.status === "done").length;
  const failCnt = results.filter((r) => r.status === "failed").length;
  const sep  = "=".repeat(76);
  const thin = "-".repeat(76);

  // ── write a wrapped block of plain text ───────────────────────────────────
  const writeLine = (text: string, size = 9, bold = false) => {
    doc.setFontSize(size);
    doc.setFont("courier", bold ? "bold" : "normal");
    doc.setTextColor(20, 20, 20);
    const wrapped: string[] = doc.splitTextToSize(text, TW);
    wrapped.forEach((line: string) => {
      if (y + LH > PH - 12) {
        doc.addPage();
        y = 15;
      }
      doc.text(line, ML, y);
      y += LH;
    });
  };

  const blankLine = () => { y += LH; };

  // ── Header ────────────────────────────────────────────────────────────────
  writeLine("AISCOPE — BULK PROMPT REPORT", 11, true);
  writeLine(`Generated : ${new Date().toLocaleString()}`);
  writeLine(`Total     : ${results.length}   Success: ${doneCnt}   Failed: ${failCnt}`);
  writeLine(sep);
  blankLine();

  // ── Prompt used ───────────────────────────────────────────────────────────
  writeLine("PROMPT USED", 9, true);
  writeLine(thin);
  writeLine(prompt.trim());
  blankLine();
  writeLine(sep);
  writeLine("RESULTS", 9, true);
  writeLine(sep);

  // ── Results ───────────────────────────────────────────────────────────────
  results.forEach((r, idx) => {
    const isOk = r.status === "done";
    blankLine();
    writeLine(`[${idx + 1}] ${r.url}`, 9, true);

    // If there are multiple provider responses, write each under the site
    if (r.responses && r.responses.length > 0) {
      r.responses.forEach((p) => {
        const meta = [p.provider, p.durationMs ? msToSec(p.durationMs) : ""].filter(Boolean).join("  |  ");
        if (meta) writeLine(`    ${meta}`);
        writeLine(thin);
        writeLine(p.response || "(no response)");
        blankLine();
      });
    } else {
      const meta = [r.provider, r.durationMs ? msToSec(r.durationMs) : ""].filter(Boolean).join("  |  ");
      if (meta) writeLine(`    ${meta}`);
      writeLine(thin);
      writeLine(isOk ? (r.response || "(no response)") : `ERROR: ${r.error ?? "Unknown error"}`);
      blankLine();
    }
  });

  // ── Footer ────────────────────────────────────────────────────────────────
  writeLine(sep);
  writeLine("Generated by AiScope  ·  aiscope.io");

  // page numbers
  const totalPages = doc.internal.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setFontSize(7);
    doc.setFont("courier", "normal");
    doc.setTextColor(130, 130, 130);
    doc.text(`Page ${p} of ${totalPages}`, PW - MR, PH - 6, { align: "right" });
  }

  doc.save(`aiscope-prompt-report-${new Date().toISOString().slice(0, 10)}.pdf`);
}

// ── Main Component ─────────────────────────────────────────────────────────
export default function BulkPromptPage() {
  const [prompt, setPrompt] = useState(DEFAULT_PROMPT);
  const [urlsRaw, setUrlsRaw] = useState("");
  const [singleUrl, setSingleUrl] = useState("");
  const [mode, setMode] = useState<"single" | "bulk">("single");
  const [results, setResults] = useState<PromptResult[]>([]);
  const [running, setRunning] = useState(false);
  const [activeResult, setActiveResult] = useState<number | null>(null);
  const abortRef = useRef<AbortController | null>(null);

  const updateResult = useCallback(
    (index: number, patch: Partial<PromptResult>) => {
      setResults((prev) => {
        const next = [...prev];
        next[index] = { ...next[index], ...patch };
        return next;
      });
    },
    []
  );

  const handleRun = async () => {
    const urls =
      mode === "single"
        ? parseUrls(singleUrl)
        : parseUrls(urlsRaw);

    if (!urls.length || !prompt.trim()) return;

    abortRef.current = new AbortController();
    setRunning(true);
    setActiveResult(0);

    const initial: PromptResult[] = urls.map((url) => ({
      url,
      status: "pending",
      response: "",
      responses: [],
      selectedResponseIndex: 0,
    }));
    setResults(initial);

    for (let i = 0; i < urls.length; i++) {
      if (abortRef.current?.signal.aborted) break;

      updateResult(i, { status: "running" });
      const start = Date.now();

      try {
        const res = await fetch("/api/prompt-run", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ url: urls[i], prompt }),
          signal: abortRef.current?.signal,
        });

        // Safely parse — if route missing, Next.js returns HTML (not JSON)
        const text = await res.text();
        let data: Record<string, unknown> = {};
        try { data = JSON.parse(text); } catch {
          updateResult(i, {
            status: "failed",
            error: res.status === 404
              ? "API route not found — ensure app/api/prompt-run/route.ts is deployed"
              : `Server returned non-JSON (HTTP ${res.status})`,
            durationMs: Date.now() - start,
          });
          continue;
        }

        if (!res.ok || data.error) {
          updateResult(i, {
            status: "failed",
            error: (data.error as string) ?? `HTTP ${res.status}`,
            durationMs: Date.now() - start,
          });
        } else {
          // support new `responses` array from API; fallback to legacy fields
          const provs = (data.responses as ProviderResponse[] | undefined) ?? (data.response ? [{ provider: data.provider ?? "", response: data.response as string ?? "", durationMs: data.durationMs as number | undefined }] : []);
          updateResult(i, {
            status: "done",
            responses: provs,
            response: provs[0]?.response ?? (data.response as string) ?? "",
            provider: provs[0]?.provider ?? (data.provider as string | undefined),
            durationMs: provs[0]?.durationMs ?? (data.durationMs as number | undefined) ?? Date.now() - start,
            selectedResponseIndex: 0,
          });
        }
      } catch (err: unknown) {
        if ((err as Error).name === "AbortError") break;
        updateResult(i, {
          status: "failed",
          error: String(err),
          durationMs: Date.now() - start,
        });
      }

      setActiveResult(Math.min(i + 1, urls.length - 1));
    }

    setRunning(false);
  };

  const handleStop = () => {
    abortRef.current?.abort();
    setRunning(false);
  };

  const doneCnt = results.filter((r) => r.status === "done").length;
  const failCnt = results.filter((r) => r.status === "failed").length;
  const progress = results.length
    ? Math.round(((doneCnt + failCnt) / results.length) * 100)
    : 0;

  const canExport = results.some((r) => r.status === "done" || r.status === "failed");

  // ── Render ───────────────────────────────────────────────────────────────
  return (
    <main
      className="min-h-screen pl-64"
      style={{ background: "#0a0b10", color: "#f0f0f5" }}
    >
      {/* ── Page Header ── */}
      <div
        className="border-b px-10 py-6"
        style={{ borderColor: "rgba(255,255,255,0.07)" }}
      >
        <div className="flex items-center justify-between">
          <div>
            <div className="flex items-center gap-3 mb-1">
              <span
                className="text-[11px] font-mono px-2.5 py-1 rounded-full border tracking-widest"
                style={{
                  color: "#c17c4e",
                  background: "rgba(193,124,78,0.08)",
                  borderColor: "rgba(193,124,78,0.25)",
                }}
              >
                NEW
              </span>
              <h1 className="text-2xl font-bold tracking-tight">
                Bulk Prompt Runner
              </h1>
            </div>
            <p className="text-sm" style={{ color: "#8b8d9e" }}>
              Write your own AI prompt · run it against one or many URLs · export
              results as PDF
            </p>
          </div>

          {canExport && (
            <button
              onClick={() => void exportToPdf(results, prompt)}
              className="flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-semibold transition-all hover:opacity-85"
              style={{ background: "#00e5ff", color: "#000" }}
            >
              ↓ Export PDF
            </button>
          )}
        </div>
      </div>

      <div className="px-10 py-8 grid grid-cols-1 xl:grid-cols-[1fr_420px] gap-6">
        {/* ── Left column ── */}
        <div className="space-y-5">

          {/* ── Prompt Editor ── */}
          <div
            className="rounded-2xl border overflow-hidden"
            style={{ background: "#111219", borderColor: "rgba(255,255,255,0.07)" }}
          >
            {/* Editor toolbar */}
            <div
              className="flex items-center justify-between px-5 py-3 border-b"
              style={{ borderColor: "rgba(255,255,255,0.07)", background: "rgba(0,0,0,0.2)" }}
            >
              <span
                className="text-[11px] font-mono tracking-widest uppercase"
                style={{ color: "#8b8d9e" }}
              >
                Custom Prompt
              </span>
              <div className="flex items-center gap-2">
                <span
                  className="text-[10px] font-mono px-2 py-0.5 rounded"
                  style={{ color: "#00e5ff", background: "rgba(0,229,255,0.08)" }}
                >
                  {"{url}"} = replaced with each website
                </span>
                <button
                  onClick={() => setPrompt(DEFAULT_PROMPT)}
                  className="text-[11px] font-mono px-3 py-1 rounded-lg border transition-all hover:opacity-80"
                  style={{
                    color: "#8b8d9e",
                    borderColor: "rgba(255,255,255,0.1)",
                    background: "transparent",
                  }}
                >
                  Reset default
                </button>
              </div>
            </div>

            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              rows={12}
              className="w-full bg-transparent border-none outline-none resize-none p-5 font-mono text-[13px] leading-relaxed"
              style={{ color: "#c9cdd4" }}
              placeholder="Write your custom prompt here. Use {url} where you want the website URL inserted…"
            />

            {/* Char count footer */}
            <div
              className="px-5 py-2.5 border-t flex items-center justify-between"
              style={{ borderColor: "rgba(255,255,255,0.07)", background: "rgba(0,0,0,0.15)" }}
            >
              <span className="text-[11px] font-mono" style={{ color: "#8b8d9e" }}>
                {prompt.length} chars · {prompt.split(/\s+/).filter(Boolean).length} words
              </span>
              <span className="text-[11px] font-mono" style={{ color: prompt.includes("{url}") ? "#00e87a" : "#ffb830" }}>
                {prompt.includes("{url}") ? "✓ {url} placeholder found" : "⚠ No {url} placeholder"}
              </span>
            </div>
          </div>

          {/* ── URL Input ── */}
          <div
            className="rounded-2xl border overflow-hidden"
            style={{ background: "#111219", borderColor: "rgba(255,255,255,0.07)" }}
          >
            {/* Mode toggle */}
            <div
              className="flex items-center gap-1 px-5 py-3 border-b"
              style={{ borderColor: "rgba(255,255,255,0.07)", background: "rgba(0,0,0,0.2)" }}
            >
              {(["single", "bulk"] as const).map((m) => (
                <button
                  key={m}
                  onClick={() => setMode(m)}
                  className="px-4 py-1.5 rounded-lg text-[12px] font-mono transition-all capitalize"
                  style={{
                    background: mode === m ? "rgba(0,229,255,0.12)" : "transparent",
                    color: mode === m ? "#00e5ff" : "#8b8d9e",
                    border: mode === m ? "1px solid rgba(0,229,255,0.3)" : "1px solid transparent",
                  }}
                >
                  {m === "single" ? "Single URL" : "Bulk URLs"}
                </button>
              ))}
            </div>

            <div className="p-5">
              {mode === "single" ? (
                <div
                  className="flex items-center rounded-xl border px-4 py-2"
                  style={{ borderColor: "rgba(255,255,255,0.1)", background: "rgba(0,0,0,0.2)" }}
                >
                  <span className="text-[13px] mr-3" style={{ color: "#8b8d9e" }}>🌐</span>
                  <input
                    type="text"
                    value={singleUrl}
                    onChange={(e) => setSingleUrl(e.target.value)}
                    onKeyDown={(e) => e.key === "Enter" && !running && handleRun()}
                    placeholder="https://yourwebsite.com"
                    className="flex-1 bg-transparent border-none outline-none text-[14px] text-white py-1.5"
                  />
                </div>
              ) : (
                <>
                  <textarea
                    value={urlsRaw}
                    onChange={(e) => setUrlsRaw(e.target.value)}
                    rows={6}
                    className="w-full bg-transparent border-none outline-none resize-none font-mono text-[13px] leading-relaxed"
                    style={{
                      color: "#c9cdd4",
                      padding: "12px 14px",
                      background: "rgba(0,0,0,0.2)",
                      borderRadius: "12px",
                      border: "1px solid rgba(255,255,255,0.08)",
                    }}
                    placeholder={"https://site1.com\nhttps://site2.com\nhttps://site3.com\n\nOne URL per line or comma-separated · max 100"}
                  />
                  <div className="mt-2 flex items-center justify-between">
                    <span className="text-[11px] font-mono" style={{ color: "#8b8d9e" }}>
                      {parseUrls(urlsRaw).length} valid URLs detected
                    </span>
                    <span className="text-[11px] font-mono" style={{ color: "#8b8d9e" }}>
                      max 100
                    </span>
                  </div>
                </>
              )}
            </div>
          </div>

          {/* ── Run / Stop button ── */}
          <div className="flex items-center gap-4">
            {!running ? (
              <button
                onClick={handleRun}
                disabled={
                  !prompt.trim() ||
                  (mode === "single" ? !singleUrl.trim() : !urlsRaw.trim())
                }
                className="flex-1 py-3.5 rounded-2xl text-sm font-bold transition-all disabled:opacity-30 disabled:cursor-not-allowed hover:opacity-85 active:scale-[0.98]"
                style={{ background: "#00e5ff", color: "#000" }}
              >
                ▶ Run Prompt
              </button>
            ) : (
              <button
                onClick={handleStop}
                className="flex-1 py-3.5 rounded-2xl text-sm font-bold transition-all hover:opacity-85"
                style={{ background: "rgba(255,90,90,0.15)", color: "#ff5a5a", border: "1px solid rgba(255,90,90,0.3)" }}
              >
                ■ Stop
              </button>
            )}
          </div>
        </div>

        {/* ── Right column: Results ── */}
        <div className="space-y-4">
          {/* Progress bar (while running) */}
          {running && results.length > 0 && (
            <div
              className="rounded-2xl border p-5"
              style={{ background: "#111219", borderColor: "rgba(255,255,255,0.07)" }}
            >
              <div className="flex items-center justify-between mb-3">
                <span className="text-[12px] font-mono" style={{ color: "#8b8d9e" }}>
                  PROGRESS
                </span>
                <span className="text-[12px] font-mono" style={{ color: "#00e5ff" }}>
                  {doneCnt + failCnt} / {results.length}
                </span>
              </div>
              <div
                className="w-full h-1.5 rounded-full overflow-hidden"
                style={{ background: "rgba(255,255,255,0.08)" }}
              >
                <div
                  className="h-full rounded-full transition-all duration-500"
                  style={{ width: `${progress}%`, background: "linear-gradient(90deg, #4285f4, #00e5ff)" }}
                />
              </div>
              <div className="flex gap-4 mt-3 text-[11px] font-mono">
                <span style={{ color: "#00e87a" }}>✓ {doneCnt} done</span>
                {failCnt > 0 && <span style={{ color: "#ff5a5a" }}>✕ {failCnt} failed</span>}
                <span style={{ color: "#8b8d9e" }}>
                  ◌ {results.filter((r) => r.status === "pending").length} pending
                </span>
              </div>
            </div>
          )}

          {/* Result cards */}
          {results.length === 0 ? (
            <div
              className="rounded-2xl border p-8 text-center"
              style={{
                background: "rgba(0,229,255,0.02)",
                borderColor: "rgba(0,229,255,0.1)",
                borderStyle: "dashed",
              }}
            >
              <div className="text-3xl mb-3">🔭</div>
              <p className="text-sm font-medium mb-1" style={{ color: "#00e5ff" }}>
                Results will appear here
              </p>
              <p className="text-[12px]" style={{ color: "#8b8d9e" }}>
                Write a prompt, add URLs, then hit Run
              </p>
            </div>
          ) : (
            results.map((r, i) => {
              const isActive = activeResult === i;
              const isRunning = r.status === "running";
              return (
                <div
                  key={r.url + i}
                  onClick={() => setActiveResult(i)}
                  className="rounded-2xl border overflow-hidden cursor-pointer transition-all"
                  style={{
                    background: "#111219",
                    borderColor: isActive
                      ? "rgba(0,229,255,0.35)"
                      : "rgba(255,255,255,0.07)",
                    boxShadow: isActive ? "0 0 0 1px rgba(0,229,255,0.15)" : "none",
                  }}
                >
                  {/* Card header */}
                  <div
                    className="flex items-center gap-3 px-4 py-3 border-b"
                    style={{ borderColor: "rgba(255,255,255,0.07)", background: "rgba(0,0,0,0.15)" }}
                  >
                    {/* Status indicator */}
                    <div className="flex-shrink-0">
                      {r.status === "running" ? (
                        <div
                          className="w-2.5 h-2.5 rounded-full animate-pulse"
                          style={{ background: "#00e5ff" }}
                        />
                      ) : r.status === "done" ? (
                        <div className="w-2.5 h-2.5 rounded-full" style={{ background: "#00e87a" }} />
                      ) : r.status === "failed" ? (
                        <div className="w-2.5 h-2.5 rounded-full" style={{ background: "#ff5a5a" }} />
                      ) : (
                        <div className="w-2.5 h-2.5 rounded-full" style={{ background: "rgba(255,255,255,0.2)" }} />
                      )}
                    </div>

                    <span
                      className="flex-1 truncate text-[12px] font-mono"
                      style={{ color: "#c9cdd4" }}
                    >
                      {r.url}
                    </span>

                    <div className="flex items-center gap-2 flex-shrink-0">
                      {/* If multiple provider responses exist, show a selector */}
                      {r.responses && r.responses.length > 1 ? (
                        <select
                          value={r.selectedResponseIndex ?? 0}
                          onChange={(e) => updateResult(i, { selectedResponseIndex: Number(e.target.value) })}
                          className="text-[10px] font-mono bg-transparent border-none"
                          style={{ color: "#8b8d9e" }}
                        >
                          {r.responses.map((p, idx) => (
                            <option key={p.provider + idx} value={idx}>
                              {p.provider}
                            </option>
                          ))}
                        </select>
                      ) : (
                        <span className="text-[10px] font-mono" style={{ color: "#8b8d9e" }}>
                          {r.provider ?? r.responses?.[0]?.provider ?? ""}
                        </span>
                      )}

                      {/* show duration for selected provider if present, otherwise top-level duration */}
                      {((r.responses && r.responses[r.selectedResponseIndex ?? 0]?.durationMs) || r.durationMs) && (
                        <span className="text-[10px] font-mono" style={{ color: "#8b8d9e" }}>
                          {msToSec(r.responses?.[r.selectedResponseIndex ?? 0]?.durationMs ?? r.durationMs)}
                        </span>
                      )}
                    </div>
                  </div>

                  {/* Card body */}
                  <div className="px-4 py-3">
                    {r.status === "pending" && (
                      <p className="text-[12px] font-mono" style={{ color: "#4b5563" }}>
                        Waiting…
                      </p>
                    )}
                    {isRunning && (
                      <div className="flex items-center gap-2">
                        <div
                          className="w-1.5 h-1.5 rounded-full animate-ping"
                          style={{ background: "#00e5ff" }}
                        />
                        <span className="text-[12px] font-mono" style={{ color: "#00e5ff" }}>
                          Running prompt…
                        </span>
                      </div>
                    )}
                    {r.status === "failed" && (
                      <p className="text-[12px]" style={{ color: "#ff5a5a" }}>
                        ✕ {r.error ?? "Unknown error"}
                      </p>
                    )}
                    {r.status === "done" && (
                      <p
                        className="text-[12px] leading-relaxed line-clamp-3"
                        style={{ color: "#8b8d9e" }}
                      >
                        {(
                          r.responses && r.responses[r.selectedResponseIndex ?? 0]
                            ? r.responses[r.selectedResponseIndex ?? 0].response
                            : r.response
                        )?.slice(0, 200)}
                        {((r.responses && r.responses[r.selectedResponseIndex ?? 0]
                          ? r.responses[r.selectedResponseIndex ?? 0].response
                          : r.response) || "").length > 200 ? "…" : ""}
                      </p>
                    )}
                  </div>
                </div>
              );
            })
          )}

          {/* Full response viewer */}
          {activeResult !== null &&
            results[activeResult] &&
            results[activeResult].status === "done" && (
              <div
                className="rounded-2xl border overflow-hidden"
                style={{ background: "#111219", borderColor: "rgba(0,229,255,0.2)" }}
              >
                <div
                  className="flex items-center justify-between px-5 py-3 border-b"
                  style={{ borderColor: "rgba(255,255,255,0.07)", background: "rgba(0,0,0,0.2)" }}
                >
                  <span className="text-[11px] font-mono tracking-widest uppercase" style={{ color: "#8b8d9e" }}>
                    Full Response
                  </span>
                  <button
                    onClick={() =>
                      navigator.clipboard.writeText(
                        results[activeResult!].responses && results[activeResult!].responses![results[activeResult!].selectedResponseIndex ?? 0]
                          ? results[activeResult!].responses![results[activeResult!].selectedResponseIndex ?? 0].response
                          : results[activeResult!].response
                      )
                    }
                    className="text-[10px] font-mono px-2.5 py-1 rounded-md transition-opacity hover:opacity-70"
                    style={{
                      color: "#00e5ff",
                      background: "rgba(0,229,255,0.08)",
                      border: "1px solid rgba(0,229,255,0.2)",
                    }}
                  >
                    Copy
                  </button>
                </div>
                <pre
                  className="p-5 text-[12px] leading-relaxed whitespace-pre-wrap font-mono overflow-y-auto"
                  style={{
                    color: "#c9cdd4",
                    maxHeight: "420px",
                  }}
                >
                  {results[activeResult].responses && results[activeResult].responses![results[activeResult].selectedResponseIndex ?? 0]
                    ? results[activeResult].responses![results[activeResult].selectedResponseIndex ?? 0].response
                    : results[activeResult].response}
                </pre>
              </div>
            )}
        </div>
      </div>
    </main>
  );
}